App_Blog/urls.py
from django.urls import path
from . import views


app_name = 'App_Blog'

urlpatterns = [
    path('', views.BlogList.as_view(), name='blog_list'),
    path('write/', views.CreateBlog.as_view() , name='create_blog'),
    path('details/<slug>', views.blog_details , name='blog_details'),
    path('liked/<pk>', views.liked , name='liked_post'),
    path('unlkied/<pk>', views.unliked , name='unliked_post'),
    path('my-blog/', views.MyBlogs.as_view() , name='my_blogs'),
    path('edit-blog/<pk>/', views.UpdateBlog.as_view() , name='edit_blog'),
]

App_Login/urls.py
from django.urls import path
from . import views

app_name = 'App_Login'

urlpatterns = [
    path('signup/', views.sign_up, name='signup'),
    path('signin/', views.login_page, name='signin'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('change-profile/', views.user_change, name='user_change'),
    path('password/', views.pass_change, name='pass_change'),
    path('change-profile-image/', views.add_pro_pic, name='add_pro_pic'),
    path('change-picture/', views.change_profile_pic, name='change_profile_pic'),
]

My_Blog_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('App_Login.urls')),
    path('blog/', include('App_Blog.urls')),
    path('', views.index, name='index')
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <title>
        {% block title %}
        Blogs Page
        {% endblock %}
    </title>
</head>

<body>

    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <div class="container">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'index' %}">Home</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'App_Login:profile' %}">Profile</a>
                </li>
                {% else %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'App_Login:signup' %}">Sign Up</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'App_Login:signin' %}">Login</a>
                </li>
                {% endif %}
            </ul>
            {% if user.is_authenticated %}
            <div class="nav-item dropdown">
                <a class="btn dropdown-toggle bg-dark text-white" type="button" id="dropdownMenuButton1"
                    data-toggle="dropdown" data-bs-toggle="dropdown">
                    {{ user.username }}
                </a>
                <div class="dropdown-menu bg-light text-secondary" aria-labelledby="dropdownMenuButton1">
                    <a href="{% url 'App_Blog:create_blog' %}" class="dropdown-item">Write Blog</a>
                    <a href="{% url 'App_Blog:my_blogs' %}" class="dropdown-item">My Blog</a>
                    <a href="{% url 'App_Login:profile' %}" class="dropdown-item">Your Profile</a>
                    <a href="{% url 'App_Login:logout' %}" class="dropdown-item">Logout</a>
                </div>
            </div>
            {% endif %}
        </div>
    </nav>

    <div class="container">
        <div class="row">
            <div class="pt-3 mt-3">
                {% block body_block %}

                {% endblock  %}
            </div>
        </div>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous">
    </script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
    -->
</body>



</html>